esphome:
  name: ${devicename}-${location_id}
  friendly_name: ${location_name} ${devicename}

esp32:
  board: esp32dev

<<: !include ../.base.yaml

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    address: 0x3C
    contrast: 50%
    update_interval: 10s
    lambda: |-
      int x = random(0, 12);  // Generates a random number from 0 to 12
      int y = random(0, 8);  // Generates a random number from 0 to 8

      // Display temperature
      it.printf(x, y, id(roboto_24), "T: %.1f°C", id(temperature).state);

      // Display humidity
      it.printf(x, 32 + y, id(roboto_24), "H: %.1f%%", id(humidity).state);

font: !include ../fonts/roboto_24.yaml
sensor: !include ../sensors/dht22.yaml
